# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: basic.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='basic.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x62\x61sic.proto\"I\n\x0bMagneticMsg\x12\x12\n\nmagnetic_x\x18\x01 \x01(\x01\x12\x12\n\nmagnetic_y\x18\x02 \x01(\x01\x12\x12\n\nmagnetic_z\x18\x03 \x01(\x01\"<\n\x0b\x44\x65\x65pNaviMsg\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\x1e\n\x08magnetic\x18\x02 \x01(\x0b\x32\x0c.MagneticMsgb\x06proto3')
)




_MAGNETICMSG = _descriptor.Descriptor(
  name='MagneticMsg',
  full_name='MagneticMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='magnetic_x', full_name='MagneticMsg.magnetic_x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='magnetic_y', full_name='MagneticMsg.magnetic_y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='magnetic_z', full_name='MagneticMsg.magnetic_z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=88,
)


_DEEPNAVIMSG = _descriptor.Descriptor(
  name='DeepNaviMsg',
  full_name='DeepNaviMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='DeepNaviMsg.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='magnetic', full_name='DeepNaviMsg.magnetic', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=150,
)

_DEEPNAVIMSG.fields_by_name['magnetic'].message_type = _MAGNETICMSG
DESCRIPTOR.message_types_by_name['MagneticMsg'] = _MAGNETICMSG
DESCRIPTOR.message_types_by_name['DeepNaviMsg'] = _DEEPNAVIMSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MagneticMsg = _reflection.GeneratedProtocolMessageType('MagneticMsg', (_message.Message,), {
  'DESCRIPTOR' : _MAGNETICMSG,
  '__module__' : 'basic_pb2'
  # @@protoc_insertion_point(class_scope:MagneticMsg)
  })
_sym_db.RegisterMessage(MagneticMsg)

DeepNaviMsg = _reflection.GeneratedProtocolMessageType('DeepNaviMsg', (_message.Message,), {
  'DESCRIPTOR' : _DEEPNAVIMSG,
  '__module__' : 'basic_pb2'
  # @@protoc_insertion_point(class_scope:DeepNaviMsg)
  })
_sym_db.RegisterMessage(DeepNaviMsg)


# @@protoc_insertion_point(module_scope)
