// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: basic.proto

package com.sysu.deepnavi.proto;

public final class Basic {
  private Basic() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MagneticMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MagneticMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double magnetic_x = 1;</code>
     * @return The magneticX.
     */
    double getMagneticX();

    /**
     * <code>double magnetic_y = 2;</code>
     * @return The magneticY.
     */
    double getMagneticY();

    /**
     * <code>double magnetic_z = 3;</code>
     * @return The magneticZ.
     */
    double getMagneticZ();
  }
  /**
   * Protobuf type {@code MagneticMsg}
   */
  public  static final class MagneticMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MagneticMsg)
      MagneticMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MagneticMsg.newBuilder() to construct.
    private MagneticMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MagneticMsg() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MagneticMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MagneticMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              magneticX_ = input.readDouble();
              break;
            }
            case 17: {

              magneticY_ = input.readDouble();
              break;
            }
            case 25: {

              magneticZ_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sysu.deepnavi.proto.Basic.internal_static_MagneticMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sysu.deepnavi.proto.Basic.internal_static_MagneticMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sysu.deepnavi.proto.Basic.MagneticMsg.class, com.sysu.deepnavi.proto.Basic.MagneticMsg.Builder.class);
    }

    public static final int MAGNETIC_X_FIELD_NUMBER = 1;
    private double magneticX_;
    /**
     * <code>double magnetic_x = 1;</code>
     * @return The magneticX.
     */
    public double getMagneticX() {
      return magneticX_;
    }

    public static final int MAGNETIC_Y_FIELD_NUMBER = 2;
    private double magneticY_;
    /**
     * <code>double magnetic_y = 2;</code>
     * @return The magneticY.
     */
    public double getMagneticY() {
      return magneticY_;
    }

    public static final int MAGNETIC_Z_FIELD_NUMBER = 3;
    private double magneticZ_;
    /**
     * <code>double magnetic_z = 3;</code>
     * @return The magneticZ.
     */
    public double getMagneticZ() {
      return magneticZ_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (magneticX_ != 0D) {
        output.writeDouble(1, magneticX_);
      }
      if (magneticY_ != 0D) {
        output.writeDouble(2, magneticY_);
      }
      if (magneticZ_ != 0D) {
        output.writeDouble(3, magneticZ_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (magneticX_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, magneticX_);
      }
      if (magneticY_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, magneticY_);
      }
      if (magneticZ_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, magneticZ_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sysu.deepnavi.proto.Basic.MagneticMsg)) {
        return super.equals(obj);
      }
      com.sysu.deepnavi.proto.Basic.MagneticMsg other = (com.sysu.deepnavi.proto.Basic.MagneticMsg) obj;

      if (java.lang.Double.doubleToLongBits(getMagneticX())
          != java.lang.Double.doubleToLongBits(
              other.getMagneticX())) return false;
      if (java.lang.Double.doubleToLongBits(getMagneticY())
          != java.lang.Double.doubleToLongBits(
              other.getMagneticY())) return false;
      if (java.lang.Double.doubleToLongBits(getMagneticZ())
          != java.lang.Double.doubleToLongBits(
              other.getMagneticZ())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + MAGNETIC_X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMagneticX()));
      hash = (37 * hash) + MAGNETIC_Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMagneticY()));
      hash = (37 * hash) + MAGNETIC_Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMagneticZ()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sysu.deepnavi.proto.Basic.MagneticMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sysu.deepnavi.proto.Basic.MagneticMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MagneticMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MagneticMsg)
        com.sysu.deepnavi.proto.Basic.MagneticMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sysu.deepnavi.proto.Basic.internal_static_MagneticMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sysu.deepnavi.proto.Basic.internal_static_MagneticMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sysu.deepnavi.proto.Basic.MagneticMsg.class, com.sysu.deepnavi.proto.Basic.MagneticMsg.Builder.class);
      }

      // Construct using com.sysu.deepnavi.proto.Basic.MagneticMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        magneticX_ = 0D;

        magneticY_ = 0D;

        magneticZ_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sysu.deepnavi.proto.Basic.internal_static_MagneticMsg_descriptor;
      }

      @java.lang.Override
      public com.sysu.deepnavi.proto.Basic.MagneticMsg getDefaultInstanceForType() {
        return com.sysu.deepnavi.proto.Basic.MagneticMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.sysu.deepnavi.proto.Basic.MagneticMsg build() {
        com.sysu.deepnavi.proto.Basic.MagneticMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sysu.deepnavi.proto.Basic.MagneticMsg buildPartial() {
        com.sysu.deepnavi.proto.Basic.MagneticMsg result = new com.sysu.deepnavi.proto.Basic.MagneticMsg(this);
        result.magneticX_ = magneticX_;
        result.magneticY_ = magneticY_;
        result.magneticZ_ = magneticZ_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sysu.deepnavi.proto.Basic.MagneticMsg) {
          return mergeFrom((com.sysu.deepnavi.proto.Basic.MagneticMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sysu.deepnavi.proto.Basic.MagneticMsg other) {
        if (other == com.sysu.deepnavi.proto.Basic.MagneticMsg.getDefaultInstance()) return this;
        if (other.getMagneticX() != 0D) {
          setMagneticX(other.getMagneticX());
        }
        if (other.getMagneticY() != 0D) {
          setMagneticY(other.getMagneticY());
        }
        if (other.getMagneticZ() != 0D) {
          setMagneticZ(other.getMagneticZ());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sysu.deepnavi.proto.Basic.MagneticMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sysu.deepnavi.proto.Basic.MagneticMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double magneticX_ ;
      /**
       * <code>double magnetic_x = 1;</code>
       * @return The magneticX.
       */
      public double getMagneticX() {
        return magneticX_;
      }
      /**
       * <code>double magnetic_x = 1;</code>
       * @param value The magneticX to set.
       * @return This builder for chaining.
       */
      public Builder setMagneticX(double value) {
        
        magneticX_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double magnetic_x = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMagneticX() {
        
        magneticX_ = 0D;
        onChanged();
        return this;
      }

      private double magneticY_ ;
      /**
       * <code>double magnetic_y = 2;</code>
       * @return The magneticY.
       */
      public double getMagneticY() {
        return magneticY_;
      }
      /**
       * <code>double magnetic_y = 2;</code>
       * @param value The magneticY to set.
       * @return This builder for chaining.
       */
      public Builder setMagneticY(double value) {
        
        magneticY_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double magnetic_y = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMagneticY() {
        
        magneticY_ = 0D;
        onChanged();
        return this;
      }

      private double magneticZ_ ;
      /**
       * <code>double magnetic_z = 3;</code>
       * @return The magneticZ.
       */
      public double getMagneticZ() {
        return magneticZ_;
      }
      /**
       * <code>double magnetic_z = 3;</code>
       * @param value The magneticZ to set.
       * @return This builder for chaining.
       */
      public Builder setMagneticZ(double value) {
        
        magneticZ_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double magnetic_z = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMagneticZ() {
        
        magneticZ_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MagneticMsg)
    }

    // @@protoc_insertion_point(class_scope:MagneticMsg)
    private static final com.sysu.deepnavi.proto.Basic.MagneticMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sysu.deepnavi.proto.Basic.MagneticMsg();
    }

    public static com.sysu.deepnavi.proto.Basic.MagneticMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MagneticMsg>
        PARSER = new com.google.protobuf.AbstractParser<MagneticMsg>() {
      @java.lang.Override
      public MagneticMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MagneticMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MagneticMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MagneticMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sysu.deepnavi.proto.Basic.MagneticMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DeepNaviMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DeepNaviMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 time = 1;</code>
     * @return The time.
     */
    long getTime();

    /**
     * <code>bytes image = 2;</code>
     * @return The image.
     */
    com.google.protobuf.ByteString getImage();

    /**
     * <code>.MagneticMsg magnetic = 3;</code>
     * @return Whether the magnetic field is set.
     */
    boolean hasMagnetic();
    /**
     * <code>.MagneticMsg magnetic = 3;</code>
     * @return The magnetic.
     */
    com.sysu.deepnavi.proto.Basic.MagneticMsg getMagnetic();
    /**
     * <code>.MagneticMsg magnetic = 3;</code>
     */
    com.sysu.deepnavi.proto.Basic.MagneticMsgOrBuilder getMagneticOrBuilder();
  }
  /**
   * Protobuf type {@code DeepNaviMsg}
   */
  public  static final class DeepNaviMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DeepNaviMsg)
      DeepNaviMsgOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DeepNaviMsg.newBuilder() to construct.
    private DeepNaviMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DeepNaviMsg() {
      image_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DeepNaviMsg();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DeepNaviMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              time_ = input.readInt64();
              break;
            }
            case 18: {

              image_ = input.readBytes();
              break;
            }
            case 26: {
              com.sysu.deepnavi.proto.Basic.MagneticMsg.Builder subBuilder = null;
              if (magnetic_ != null) {
                subBuilder = magnetic_.toBuilder();
              }
              magnetic_ = input.readMessage(com.sysu.deepnavi.proto.Basic.MagneticMsg.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(magnetic_);
                magnetic_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.sysu.deepnavi.proto.Basic.internal_static_DeepNaviMsg_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.sysu.deepnavi.proto.Basic.internal_static_DeepNaviMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.sysu.deepnavi.proto.Basic.DeepNaviMsg.class, com.sysu.deepnavi.proto.Basic.DeepNaviMsg.Builder.class);
    }

    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>int64 time = 1;</code>
     * @return The time.
     */
    public long getTime() {
      return time_;
    }

    public static final int IMAGE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString image_;
    /**
     * <code>bytes image = 2;</code>
     * @return The image.
     */
    public com.google.protobuf.ByteString getImage() {
      return image_;
    }

    public static final int MAGNETIC_FIELD_NUMBER = 3;
    private com.sysu.deepnavi.proto.Basic.MagneticMsg magnetic_;
    /**
     * <code>.MagneticMsg magnetic = 3;</code>
     * @return Whether the magnetic field is set.
     */
    public boolean hasMagnetic() {
      return magnetic_ != null;
    }
    /**
     * <code>.MagneticMsg magnetic = 3;</code>
     * @return The magnetic.
     */
    public com.sysu.deepnavi.proto.Basic.MagneticMsg getMagnetic() {
      return magnetic_ == null ? com.sysu.deepnavi.proto.Basic.MagneticMsg.getDefaultInstance() : magnetic_;
    }
    /**
     * <code>.MagneticMsg magnetic = 3;</code>
     */
    public com.sysu.deepnavi.proto.Basic.MagneticMsgOrBuilder getMagneticOrBuilder() {
      return getMagnetic();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (time_ != 0L) {
        output.writeInt64(1, time_);
      }
      if (!image_.isEmpty()) {
        output.writeBytes(2, image_);
      }
      if (magnetic_ != null) {
        output.writeMessage(3, getMagnetic());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (time_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, time_);
      }
      if (!image_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, image_);
      }
      if (magnetic_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getMagnetic());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.sysu.deepnavi.proto.Basic.DeepNaviMsg)) {
        return super.equals(obj);
      }
      com.sysu.deepnavi.proto.Basic.DeepNaviMsg other = (com.sysu.deepnavi.proto.Basic.DeepNaviMsg) obj;

      if (getTime()
          != other.getTime()) return false;
      if (!getImage()
          .equals(other.getImage())) return false;
      if (hasMagnetic() != other.hasMagnetic()) return false;
      if (hasMagnetic()) {
        if (!getMagnetic()
            .equals(other.getMagnetic())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
      hash = (37 * hash) + IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getImage().hashCode();
      if (hasMagnetic()) {
        hash = (37 * hash) + MAGNETIC_FIELD_NUMBER;
        hash = (53 * hash) + getMagnetic().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.sysu.deepnavi.proto.Basic.DeepNaviMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DeepNaviMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DeepNaviMsg)
        com.sysu.deepnavi.proto.Basic.DeepNaviMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.sysu.deepnavi.proto.Basic.internal_static_DeepNaviMsg_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.sysu.deepnavi.proto.Basic.internal_static_DeepNaviMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.sysu.deepnavi.proto.Basic.DeepNaviMsg.class, com.sysu.deepnavi.proto.Basic.DeepNaviMsg.Builder.class);
      }

      // Construct using com.sysu.deepnavi.proto.Basic.DeepNaviMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        time_ = 0L;

        image_ = com.google.protobuf.ByteString.EMPTY;

        if (magneticBuilder_ == null) {
          magnetic_ = null;
        } else {
          magnetic_ = null;
          magneticBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.sysu.deepnavi.proto.Basic.internal_static_DeepNaviMsg_descriptor;
      }

      @java.lang.Override
      public com.sysu.deepnavi.proto.Basic.DeepNaviMsg getDefaultInstanceForType() {
        return com.sysu.deepnavi.proto.Basic.DeepNaviMsg.getDefaultInstance();
      }

      @java.lang.Override
      public com.sysu.deepnavi.proto.Basic.DeepNaviMsg build() {
        com.sysu.deepnavi.proto.Basic.DeepNaviMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.sysu.deepnavi.proto.Basic.DeepNaviMsg buildPartial() {
        com.sysu.deepnavi.proto.Basic.DeepNaviMsg result = new com.sysu.deepnavi.proto.Basic.DeepNaviMsg(this);
        result.time_ = time_;
        result.image_ = image_;
        if (magneticBuilder_ == null) {
          result.magnetic_ = magnetic_;
        } else {
          result.magnetic_ = magneticBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.sysu.deepnavi.proto.Basic.DeepNaviMsg) {
          return mergeFrom((com.sysu.deepnavi.proto.Basic.DeepNaviMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.sysu.deepnavi.proto.Basic.DeepNaviMsg other) {
        if (other == com.sysu.deepnavi.proto.Basic.DeepNaviMsg.getDefaultInstance()) return this;
        if (other.getTime() != 0L) {
          setTime(other.getTime());
        }
        if (other.getImage() != com.google.protobuf.ByteString.EMPTY) {
          setImage(other.getImage());
        }
        if (other.hasMagnetic()) {
          mergeMagnetic(other.getMagnetic());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.sysu.deepnavi.proto.Basic.DeepNaviMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.sysu.deepnavi.proto.Basic.DeepNaviMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long time_ ;
      /**
       * <code>int64 time = 1;</code>
       * @return The time.
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>int64 time = 1;</code>
       * @param value The time to set.
       * @return This builder for chaining.
       */
      public Builder setTime(long value) {
        
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 time = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTime() {
        
        time_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString image_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes image = 2;</code>
       * @return The image.
       */
      public com.google.protobuf.ByteString getImage() {
        return image_;
      }
      /**
       * <code>bytes image = 2;</code>
       * @param value The image to set.
       * @return This builder for chaining.
       */
      public Builder setImage(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        image_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes image = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearImage() {
        
        image_ = getDefaultInstance().getImage();
        onChanged();
        return this;
      }

      private com.sysu.deepnavi.proto.Basic.MagneticMsg magnetic_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sysu.deepnavi.proto.Basic.MagneticMsg, com.sysu.deepnavi.proto.Basic.MagneticMsg.Builder, com.sysu.deepnavi.proto.Basic.MagneticMsgOrBuilder> magneticBuilder_;
      /**
       * <code>.MagneticMsg magnetic = 3;</code>
       * @return Whether the magnetic field is set.
       */
      public boolean hasMagnetic() {
        return magneticBuilder_ != null || magnetic_ != null;
      }
      /**
       * <code>.MagneticMsg magnetic = 3;</code>
       * @return The magnetic.
       */
      public com.sysu.deepnavi.proto.Basic.MagneticMsg getMagnetic() {
        if (magneticBuilder_ == null) {
          return magnetic_ == null ? com.sysu.deepnavi.proto.Basic.MagneticMsg.getDefaultInstance() : magnetic_;
        } else {
          return magneticBuilder_.getMessage();
        }
      }
      /**
       * <code>.MagneticMsg magnetic = 3;</code>
       */
      public Builder setMagnetic(com.sysu.deepnavi.proto.Basic.MagneticMsg value) {
        if (magneticBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          magnetic_ = value;
          onChanged();
        } else {
          magneticBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.MagneticMsg magnetic = 3;</code>
       */
      public Builder setMagnetic(
          com.sysu.deepnavi.proto.Basic.MagneticMsg.Builder builderForValue) {
        if (magneticBuilder_ == null) {
          magnetic_ = builderForValue.build();
          onChanged();
        } else {
          magneticBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.MagneticMsg magnetic = 3;</code>
       */
      public Builder mergeMagnetic(com.sysu.deepnavi.proto.Basic.MagneticMsg value) {
        if (magneticBuilder_ == null) {
          if (magnetic_ != null) {
            magnetic_ =
              com.sysu.deepnavi.proto.Basic.MagneticMsg.newBuilder(magnetic_).mergeFrom(value).buildPartial();
          } else {
            magnetic_ = value;
          }
          onChanged();
        } else {
          magneticBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.MagneticMsg magnetic = 3;</code>
       */
      public Builder clearMagnetic() {
        if (magneticBuilder_ == null) {
          magnetic_ = null;
          onChanged();
        } else {
          magnetic_ = null;
          magneticBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.MagneticMsg magnetic = 3;</code>
       */
      public com.sysu.deepnavi.proto.Basic.MagneticMsg.Builder getMagneticBuilder() {
        
        onChanged();
        return getMagneticFieldBuilder().getBuilder();
      }
      /**
       * <code>.MagneticMsg magnetic = 3;</code>
       */
      public com.sysu.deepnavi.proto.Basic.MagneticMsgOrBuilder getMagneticOrBuilder() {
        if (magneticBuilder_ != null) {
          return magneticBuilder_.getMessageOrBuilder();
        } else {
          return magnetic_ == null ?
              com.sysu.deepnavi.proto.Basic.MagneticMsg.getDefaultInstance() : magnetic_;
        }
      }
      /**
       * <code>.MagneticMsg magnetic = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.sysu.deepnavi.proto.Basic.MagneticMsg, com.sysu.deepnavi.proto.Basic.MagneticMsg.Builder, com.sysu.deepnavi.proto.Basic.MagneticMsgOrBuilder> 
          getMagneticFieldBuilder() {
        if (magneticBuilder_ == null) {
          magneticBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.sysu.deepnavi.proto.Basic.MagneticMsg, com.sysu.deepnavi.proto.Basic.MagneticMsg.Builder, com.sysu.deepnavi.proto.Basic.MagneticMsgOrBuilder>(
                  getMagnetic(),
                  getParentForChildren(),
                  isClean());
          magnetic_ = null;
        }
        return magneticBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DeepNaviMsg)
    }

    // @@protoc_insertion_point(class_scope:DeepNaviMsg)
    private static final com.sysu.deepnavi.proto.Basic.DeepNaviMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.sysu.deepnavi.proto.Basic.DeepNaviMsg();
    }

    public static com.sysu.deepnavi.proto.Basic.DeepNaviMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DeepNaviMsg>
        PARSER = new com.google.protobuf.AbstractParser<DeepNaviMsg>() {
      @java.lang.Override
      public DeepNaviMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DeepNaviMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DeepNaviMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DeepNaviMsg> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.sysu.deepnavi.proto.Basic.DeepNaviMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MagneticMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MagneticMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeepNaviMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeepNaviMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013basic.proto\"I\n\013MagneticMsg\022\022\n\nmagnetic" +
      "_x\030\001 \001(\001\022\022\n\nmagnetic_y\030\002 \001(\001\022\022\n\nmagnetic" +
      "_z\030\003 \001(\001\"J\n\013DeepNaviMsg\022\014\n\004time\030\001 \001(\003\022\r\n" +
      "\005image\030\002 \001(\014\022\036\n\010magnetic\030\003 \001(\0132\014.Magneti" +
      "cMsgB \n\027com.sysu.deepnavi.protoB\005Basicb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MagneticMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MagneticMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MagneticMsg_descriptor,
        new java.lang.String[] { "MagneticX", "MagneticY", "MagneticZ", });
    internal_static_DeepNaviMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DeepNaviMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeepNaviMsg_descriptor,
        new java.lang.String[] { "Time", "Image", "Magnetic", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
